### PR TITLE
added courses

### PR DESCRIPTION
**Pull request by kchhabra99**

### CODE REVIEW

**Comment by hardesh** [comment]
I think instead of this, directly adding the robotics specialization would be better?

**Comment by kchhabra99** [comment]
> I think instead of this, directly adding the robotics specialization would be better?

Yeah, I guess we could do that but this way people can actually choose if let's say they just want to do a course on perception without actually going through the specialization list

**Comment by mihirk284** [comment]
@kchhabra99 How about having a bullet point as robotics specialisation and sub bullet points being the individual courses?

**Comment by kchhabra99** [comment]
> @kchhabra99 How about having a bullet point as robotics specialisation and sub bullet points being the individual courses?

yeah, that sounds better. I'll commit the changes

**Pull request merged**
